### ISSUE TITLE
cannot build project with Angular6

### ISSUE THREAD

**Issue by elvirusHDS** [mjaric/ng2-heremaps#2]
Hello, I have the following issue:

I followed the provided instructions to integrate ng2-heremaps into my Angular6-project, but unfortunately, when start `ng serve`, I get the following error:

`ERROR in ./node_modules/ng2-heremaps/index.ts
Module build failed: Error: {local-path-to-angular}\ClientApp\node_modules\ng2-heremaps\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile ({local-path-to-angular}\ClientApp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:749:23)
    at plugin.done.then ({local-path-to-angular}\ClientApp\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
i ｢wdm｣: Failed to compile.`

Can you please help me? Am I doing something wrong or does the library needs to be updated?
If you need more information, please let me know.

Best regards,
elvirus

**Comment by mjaric** [comment]
I never tested this with Angular 6, but apparently it requires a bit of polishing according to this [document](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) 

I'm not able to fix this quickly at the moment, but if this is urgent to you feel free to make pull request

**Comment by elvirusHDS** [comment]
Thank you for your reply. After taking a brief look into the documentation of the Angular Package Format I realized that I do not understand which work should be done here. I am fairly new to the Angular world and never made npm packages before.
I would really like to support you here, I think I just don't have the required knowledge.
There is something mentioned in the error message of including the file in tsconfig.json... Could that be a workaround for me in order to use your lib? Unfortunately, I was not able to get it working. Do you have an idea how to make it work with tsconfig? Can this be done?

Best regards,
elvirus

**Comment by elvirusHDS** [comment]
I tried to build a new version of the library using the angular-library-starter you linked here. I got several errors during the build and addressed one after the other. There where changes in some imports (f. i. rxjs), some types have changed also.
After I got rid of all errors in the build console, the build failed again but without any error output. :-(
So, unfortunately, I must give up here. I was really exited when I found your library but since I have to implement a map feature in the current sprint, I have to fallback to using OSM which is really a bummer for me. :-(
Maybe, if you find the time to update the lib (which seems to be the only one available in the web), I might change my code to use it then.

Cheers,
elvirus

**Comment by jedsmith13** [comment]
@elvirusHDS Let me take a look at this today. I have it working locally, so it should be workable. Though admittedly I am just using it as a module in my application.

**Comment by jedsmith13** [comment]
@elvirusHDS I created a pull request where I switched the code over to using angular-library-starter. #3 

I tested by building and then copying the contents of the dist folder into the node_modules/ng2-heremaps folder of a new app where I had installed ng2-heremaps. It seems to work fine now.

@mjaric If my changes look good could you merge the pull request and deploy to NPM. Thanks!

**Comment by mjaric** [comment]
checking. Will get back to you as soon as I try it in simple app

**Comment by mjaric** [comment]
ok, version 0.2 is in npm now. @jedsmith13 good job on wrapping all build, packing and publishing stuff!!! 

I have to download angular-cli since I didn't build any apps recently in angular. So give me few more minutes to check this build.

**Comment by mjaric** [comment]
works! so you can use it from npmjs.org by adding 
`"ng2-heremaps": "~0.2.0",` into dependencies in package.json

**Comment by mjaric** [comment]
I'm not sure if peer dependency is required since it would be good to allow other people that uses older angular to use this lib too. 

@elvirusHDS please confirm that it works for you now.

Thanks!

**Comment by elvirusHDS** [comment]
WOW! Guys, you are awesome!
I updated the dependency and the project builds now. That's great for the start!
You deserve a cake for that!

I obtained an appID and an apiCode at heremaps and when I start the application I get the following error:
`Error: Uncaught (in promise): TypeError: Cannot read property 'UI' of undefined TypeError: Cannot read property 'UI' of undefined at https://localhost:5001/vendor.js:143920:44 at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (https://localhost:5001/polyfills.js:2741:26) at Object.onInvoke (https://localhost:5001/vendor.js:58219:33) at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (https://localhost:5001/polyfills.js:2740:32) at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (https://localhost:5001/polyfills.js:2491:43) at https://localhost:5001/polyfills.js:3225:34 at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://localhost:5001/polyfills.js:2774:31) at Object.onInvokeTask (https://localhost:5001/vendor.js:58210:33) at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://localhost:5001/polyfills.js:2773:36) at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (https://localhost:5001/polyfills.js:2541:47)`
Can it be that I am doing something wrong here or is it in the library?

my here config:
export const hereConfig = {
  appId: '{appId from heremaps}',
  apiKey: '{appCode from heremaps}',
  apiVersion: '3.0',
  libraries: ['core', 'service']
}

When I remove 'geometry from the libraries array in the config, I get basically the same error but with UI instead of geometry...

excerpt from my app.module.ts:
[...]
import { HereMapsModule } from 'ng2-heremaps';
import { hereConfig } from './config/here-maps'
[...]
imports: [
[...]
    HereMapsModule.forRoot(hereConfig),
  ],

my mapComponent:
<heremap [center]="{latitude: 52.2688736, longitude: 10.5267696}"></heremap>

Any ideas? Did you guys see any map data?
Thank you so far,
best regards,
elvirus

**Comment by mjaric** [comment]
I think you need to change config and include library `'ui'` too. libraries

```typescript
export const hereConfig = {
  appId: '{appId from heremaps}',
  apiKey: '{appCode from heremaps}',
  apiVersion: '3.0',
  libraries: ['core', 'service', 'ui']
}
```

[Here](https://developer.here.com/documentation/maps/topics/overview.html#overview__modules) is what dependency matrix looks like. So just add module name (not file name it will be generated for you under the hud). So to summarize libs:

- `core` - always required
- `service` - This module supports map tile retrieval, routing, geocoding, etc.
- `mapevents` - This module provides functionality to enable user-interaction with the map, including map panning and pinch-to-zoom
- `ui` - This module provides a set of pre-built cross-browser UI components (such as base map settings, zoom control, map scale) that can be added to the map. It also provides functionality to display location-specific info bubbles with arbitrary HTML content on the map.
- `clustering` - This module provides functionality for marker clustering.
- `data` - This module provides set of classes for display of KML and GeoJSON data.
- `places` - This module simplifies the use of REST places API. (requires `service`)
- `pano` - This module provides access to HERE StreetLevel imagery on WebGL-enabled devices. It supports switching the map to the StreetLevel rendering mode and navigation through StreetLevel panoramas. (requires `service`)

**Comment by elvirusHDS** [comment]
Ok,
awesome! It seems to be working. I have no errors and the map ui is shown. There are no map tiles displayed though but I think this is a problem of my container hierarchy. I should be able to figure this out on my own.

thank you so much!
Awesome lib! Awesome work!

Cheers,
elvirus
